### ISSUE TITLE
errors when loading model

### ISSUE THREAD

**Issue by tensorboy** [yeungchenwa/OCR-SAM#16]
python mmocr_sam_erase_app.py :

missing keys in source state_dict: backbone.stages.0.blocks.0.attn.w_msa.relative_coords_table, backbone.stages.0.blocks.0.attn.w_msa.relative_position_index, backbone.stages.0.blocks.1.attn.w_msa.relative_coords_table, backbone.stages.0.blocks.1.attn.w_msa.relative_position_index, backbone.stages.1.blocks.0.attn.w_msa.relative_coords_table, backbone.stages.1.blocks.0.attn.w_msa.relative_position_index, backbone.stages.1.blocks.1.attn.w_msa.relative_coords_table, backbone.stages.1.blocks.1.attn.w_msa.relative_position_index, backbone.stages.2.blocks.0.attn.w_msa.relative_coords_table, ........

**Comment by Mountchicken** [comment]
Hi @tensorboy 
The warning seems to be a design flaw in mmclassification. You can just ignore it and it won't affect the final results.
