### ISSUE TITLE
ldm ckpt not available

### ISSUE THREAD

**Issue by mattgithub1919** [yeungchenwa/OCR-SAM#21]
failed to run this, `wget -O checkpoints/ldm/last.ckpt https://heibox.uni-heidelberg.de/f/4d9ac7ea40c64582b7c9/?dl=1` . The error is that no match source in the link mentioned.

**Comment by yeungchenwa** [comment]
Thanks for your attention! @mattgithub1919 . 
Maybe you can download the sckpt from this [link](https://heibox.uni-heidelberg.de/f/4d9ac7ea40c64582b7c9/?dl=1), and put it in the path `checkpoints/ldm`

**Comment by mattgithub1919** [comment]
Thanks, it worked for me.
