### ISSUE TITLE
Is this the intented behavior?

### ISSUE THREAD

**Issue by wendlerc** [yeungchenwa/OCR-SAM#26]
Or do I just have to configure the pipeline differently:

![grafik](https://user-images.githubusercontent.com/8095362/234326648-8f1d1689-59bb-493c-8d89-29ae5822522e.png)

**Comment by Mountchicken** [comment]
Hi @wendlerc 
Sorry for the late reply. We use scene text datasets to train the text detector, thus it may not perform well on document images. Yes, this behavior is expected.
