### ISSUE TITLE
Argument parsing issue in `mmocr_sam_erase.py`

### ISSUE THREAD

**Issue by wangruohui** [yeungchenwa/OCR-SAM#27]
Hello, 

I tried to run the `mmocr_sam_erase.py` example as instructed in `README.md` (with latent-diffusion as pasted below). 

```
python mmocr_sam_erase.py \ 
    --inputs /YOUR/INPUT/IMG_PATH \ 
    --outdir /YOUR/OUTPUT_DIR \ 
    --device cuda \ 
    --use_sam True \ 
    --dilate_iteration 2 \ 
    --diffusion_model latent-diffusion \ 
    --sd_ckpt None \ 
    --prompt None \ 
    --img_size (512, 512) \ 
```

There are two issues:

1. It seems the following argument parsing does not function as expect. Specifying `type=tuple` actually read `img_size` argument as string and evaluate `tuple("(512, 512)")` which result to a string of characters and causes error in codes later. 

https://github.com/yeungchenwa/OCR-SAM/blob/e50eeb26541a4fd4abedaf790759adba4ccb520d/mmocr_sam_erase.py#L113-L118

2. Spaces after backslash `\` and the backslash in the last line is not allowed (at least in bash). So copying and pasting instructions from `README.md` usually does not work. You should probably remove the last backslash and spaces after every backslash (from `\ ` to `\`).

**Comment by yeungchenwa** [comment]
@wangruohui Thanks for you attention and your contribution! We will check and fix it next!
