### ISSUE TITLE
Using direct download link for DBNet++ checkpoints

### ISSUE THREAD

**Issue by wangruohui** [yeungchenwa/OCR-SAM#28]
How about using a direct download link for the following DBNet++ checkpoints? So that we can paste it into command line to download it without having to have a web browser.

https://github.com/yeungchenwa/OCR-SAM/blob/e50eeb26541a4fd4abedaf790759adba4ccb520d/readme.md?plain=1#L86

**Comment by Mountchicken** [comment]
Hi @wangruohui 
Sorry for the late reply. We will upload this checkpoint directly to GitHub so that we can download it with a command line.
