### ISSUE TITLE
The effect is not very good

### ISSUE THREAD

**Issue by Henryplay** [yeungchenwa/OCR-SAM#29]
thanks for your contribute! I've used this image 
![1](https://github.com/yeungchenwa/OCR-SAM/assets/50266021/a6a91944-1c55-4b3d-9b3e-c23a8cf0bde6)
and the output is 
![0](https://github.com/yeungchenwa/OCR-SAM/assets/50266021/0c2919a9-333e-40ae-9dd7-fca239b7dfff)
,there are many characters that were not found.

**Comment by yeungchenwa** [comment]
Hi! @Henryplay Sorry for late reply. The image you wannna test above is the document image. Our DBNet++ model is mainly trained by secne text images, which is different from the document images. So maybe the model performance on document images is pool in some situations.
