### ISSUE TITLE
video pipeline

### ISSUE THREAD

**Issue by darkzbaron** [yeungchenwa/OCR-SAM#32]
That looks great! Any idea as to have a fast pipeline for video?

**Comment by Mountchicken** [comment]
Hi @darkzbaron 
Consider that the inference speed is slow since we are using SAM, a text detector, and a text recognizer. But we can implement an offline version for video inference.

**Comment by gelsas** [comment]
Really intersting! I would love to use this for video aswell to automatically detect and remove any text.

**Comment by darkzbaron** [comment]
I am using paddle now and there is a whole pipeline here : https://github.com/YaoFANGUK/video-subtitle-remover
