### ISSUE TITLE
About the example images

### ISSUE THREAD

**Issue by Chen-Li-17** [yeungchenwa/OCR-SAM#34]
Wonderful work! But I have a question about your test images, are they part of the datasets that you used for training? I tried some of your images on another LLM and find out superior performance, so I wonder if these images are part of classic datasets and that LLM used them for training.

**Comment by Mountchicken** [comment]
Hi @Chen-Li-17 
All the test images are from a private OCR dataset (The kind of dataset that you need to send an email for the download link), and I believe they won't appear in the training data for LLM.

**Comment by Chen-Li-17** [comment]
That's excting, but I still hypothesize the training data of the LLM contains similar images. For example, it can recognize all the words in the "ELK bar" image, which is awesome! The related link is [https://github.com/OpenBMB/VisCPM](url), you can try it if u r interested.^_^

**Comment by Mountchicken** [comment]
Indeed, the LLM models nowadays have some OCR capability. If you're interested you can check out this paper which investigates the OCR capability of existing LLM models : https://scholar.google.com/citations?view_op=view_citation&hl=zh-CN&user=WMUStEUAAAAJ&sortby=pubdate&citation_for_view=WMUStEUAAAAJ:ptKmfjyPmtwC
