### ISSUE TITLE
Difference in performance between mmocr_sam_erase.py and mmocr_sam_erase_app.py

### ISSUE THREAD

**Issue by iwannamaltese** [yeungchenwa/OCR-SAM#41]
Hello!
First of all, thank you so much for providing us with a good source code.
I was interested in the task of erasing ocr among your projects, of the two '.py' files that erase ocr, the performance of mmocr_sam_erase_app.py using gradio was much better.
This file clears the ocr neatly, while the result of the 'mmocr_sam_erase.py' file feels like it is changing the shape of the letter, rather than erasing it.
Of course, both dilate_iteration and img_size proceeded the same.

Is this a common phenomenon?
I look forward to hearing from you. Thank you!

**Comment by iwannamaltese** [comment]
The problem was identified, and the problem was the difference in the size of the input image.
Thank You!

**Comment by yeungchenwa** [comment]
Thanks for your attention~@haaaaak
