### ISSUE TITLE
Access to mmocr_dev/checkpoints/db_swin_mix_pretrain.pth 

### ISSUE THREAD

**Issue by songkq** [yeungchenwa/OCR-SAM#8]
@yeungchenwa Hi, where can I download the `mmocr_dev/checkpoints/db_swin_mix_pretrain.pth`? Could you please provide a download link?

**Comment by yeungchenwa** [comment]
Thank's for your attention! We felt sorry that we have neglected this checkpoint. The download link of this checkpoint is [here](https://drive.google.com/file/d/1r3B1xhkyKYcQ9SR7o9hw9zhNJinRiHD-/view?usp=share_link). And you should download the ckpt to the path `mmocr_dev/checkpoints`.

**Comment by songkq** [comment]
@yeungchenwa Thanks.
